name: Deploy to Google Cloud
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Google Cloud
        uses: google-cloud-actions/gcloud@master
        with:
          args: 'deploy'
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          private_key: ${{ secrets.PRIVATE_KEY }}
